[workspace]
members = ["data", "business", "utils", "web_api", "db"]
default-members = ["web_api", "data"]
resolver = "2"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1

[profile.dev]
lto = false
opt-level = 0
codegen-units = 256
